// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDb5tEd9FQAyNESAjf7EsyUbT_-auPqt0',
    appId: '1:711520800549:web:75a6ec1302175e9f1154cc',
    messagingSenderId: '711520800549',
    projectId: 'thinkthank-424242',
    authDomain: 'thinkthank-424242.firebaseapp.com',
    storageBucket: 'thinkthank-424242.appspot.com',
    measurementId: 'G-JX829FTHQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvhf4XbwT3v-VHePTFPs9BNvevUbVl_aI',
    appId: '1:711520800549:android:809046a118622cb71154cc',
    messagingSenderId: '711520800549',
    projectId: 'thinkthank-424242',
    storageBucket: 'thinkthank-424242.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDeG7yYdjmm89XWCpFDNe_kYN-Mtr4vAM',
    appId: '1:711520800549:ios:fb7d054b5a723d591154cc',
    messagingSenderId: '711520800549',
    projectId: 'thinkthank-424242',
    storageBucket: 'thinkthank-424242.appspot.com',
    androidClientId: '711520800549-j9ip9f7469s4d0i7cou4a9lgmkk7tho1.apps.googleusercontent.com',
    iosClientId: '711520800549-3hp32l6j20e09poj6ctdeoq9llb5f563.apps.googleusercontent.com',
    iosBundleId: 'com.example.thinktank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDeG7yYdjmm89XWCpFDNe_kYN-Mtr4vAM',
    appId: '1:711520800549:ios:fb7d054b5a723d591154cc',
    messagingSenderId: '711520800549',
    projectId: 'thinkthank-424242',
    storageBucket: 'thinkthank-424242.appspot.com',
    androidClientId: '711520800549-j9ip9f7469s4d0i7cou4a9lgmkk7tho1.apps.googleusercontent.com',
    iosClientId: '711520800549-3hp32l6j20e09poj6ctdeoq9llb5f563.apps.googleusercontent.com',
    iosBundleId: 'com.example.thinktank',
  );
}
